### ISSUE TITLE
OpenCV not work

### ISSUE THREAD

**Issue by AndrewSivrit** [ganyc717/Darknet-On-OpenCL#2]
Hi @ganyc717 
I want to run your code on the VS2015 and windows 7. 
In mode with OPENCV, but this mode not working 
1. Not included headers for opencv in demo.cpp
2. Not defined pthread_t is not defined in demo.cpp
And other..

**Comment by ganyc717** [comment]
Hi @AndrewSivrit 
The OpenCV mode is not supported yet. I will add OpenCV support soon.

**Comment by ganyc717** [comment]
Hi @AndrewSivrit 
I have already add the OpenCV support. Thank you for your ticket.
